#!/bin/sh

Result_Path=`pwd`/result

Protocol_Path=`pwd`/test_sig

#gcc_path=`pwd`/tools/gcc-linaro-arm-linux-gnueabihf-4.9-2014.09_linux/bin
#gcc_path=`pwd`/tools/arm-cortexa9-linux-gnueabihf/gcc-4.7.3-glibc-2.16.0-binutils-2.22-kernel-3.6-sanitized/bin
gcc_path=/usr/bin/gcc

cd $Protocol_Path
#Application
#$gcc_path/arm-linux-gnueabihf-g++ -O2 -Wall -DLINUX -o sap sap.c dll.c dll_algrthm.c dll_idp.c dll_odp.c dll_interleave.c ccl_dl.c ccl_ul.c ccl_thread.c ccl_fun.c -I ../inc -lpthread

#$gcc_path/arm-cortexa9-linux-gnueabihf-g++ -O2 -Wall -DLINUX -o NasTest sigtest.c -I ../inc  -lpthread
$gcc_path -O2 -Wall -DLINUX -o NasTest sigtest.c -I ../inc  -lpthread

if [ -e NasTest ]
then
	echo "~~~~ok~~"
fi


if [ -e NasTest ]
then
	cp NasTest $Result_Path
	rm NasTest
fi


#cd $Adapter_Path
#$gcc_path/arm-cortexa9-linux-gnueabihf-g++ -O2 -Wall -DLINUX -o nm nm.c common.c md5.c
#if [ -e nm ]
#then
#    cp nm $Result_Path
#    rm nm
#fi


