all: sigtest  caozhi


clean:
	rm sigtest caozhi

sigtest: sigtest.c
	gcc -o sigtest sigtest.c



char_test: char_test.c
	gcc -o char_test	char_test.c
	
	
caozhi: caozhi.c
	gcc -o caozhi	caozhi.c